version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: leet_role
      POSTGRES_PASSWORD: thing
      POSTGRES_DB: leet
    ports:
      - '5433:5432'



